language: go

go:
    - tip
    - 1.5.1
    - 1.5
    - 1.4.3
    - 1.4.2
    - 1.4.1
    - 1.4
    - 1.3.3
    - 1.3.2
    - 1.3.1
    - 1.3
    - 1.2.2
    - 1.1
    - 1.1.2
    - 1.1.1
    - 1.0.3
    - 1.0.2
    - 1.0.1
